forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-stdlib',
    :git => "https://github.com/puppetlabs/puppetlabs-stdlib.git"
mod 'puppetlabs/ntp',
    :git => "https://github.com/puppetlabs/puppetlabs-ntp.git"
mod 'ajcrowe/supervisord'
mod 'puppetlabs/apt'
mod 'puppetlabs/concat', '1.2.5'
mod 'puppetlabs/apache'

mod 'datacentred/dockerbuild',
    :git => "https://dc-jenkins:27485be45693278ac9be41d4540c8ac4f1adc6b7@github.com/datacentred/dockerbuild.git"

mod 'openstack/neutron'
mod 'openstack/keystone',
    :git    => "https://github.com/openstack/puppet-keystone.git",
    :branch => "master"
mod 'openstack/nova'
mod 'openstack/openstacklib',
    :git    => "https://github.com/openstack/puppet-openstacklib.git",
    :branch => "master"
mod 'openstack/vswitch'
mod 'openstack/cinder'
mod 'openstack/oslo',
    :git    => "https://github.com/openstack/puppet-oslo.git",
    :branch => "master"
mod 'puppetlabs-inifile'
mod 'puppetlabs-mysql'
